# Generated by Django 3.1.7 on 2021-03-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_password1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=68),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password1',
            field=models.CharField(default='', max_length=68),
        ),
    ]
