# Generated by Django 3.1.7 on 2021-02-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comfyapi', '0002_auto_20210221_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='home', max_length=150),
        ),
    ]
