# Generated by Django 3.1.7 on 2021-02-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comfyapi', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.BooleanField(default=True),
        ),
    ]
