# Generated by Django 3.1.7 on 2021-02-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comfyapi', '0005_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='countInStock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
