# Generated by Django 3.1.7 on 2021-03-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comfyapi', '0009_auto_20210302_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingprofile',
            old_name='user',
            new_name='owner',
        ),
    ]
