# Generated by Django 3.1.7 on 2021-03-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comfyapi', '0010_auto_20210302_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingprofile',
            name='phone_no',
        ),
    ]
