# Generated by Django 3.1.7 on 2021-03-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comfyapi', '0015_auto_20210305_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_profile', to='comfyapi.shippingprofile'),
        ),
    ]
